from typing import Protocol
from domain.entities.metadata import Metadata

class MetadataRepositoryProtocol(Protocol):
    def save(self, metadata: Metadata) -> Metadata: ...
    def find_all(self) -> list[Metadata]: ...
    def find_by_title(self, title: str) -> Metadata | None: ...
