from typing import Protocol
from domain.entities.transcoding_job import TranscodingJob

class TranscodingRepositoryProtocol(Protocol):
    def save(self, job: TranscodingJob) -> TranscodingJob: ...
    def update_status(self, job_id: int, status: str) -> TranscodingJob | None: ...
    def find_all(self) -> list[TranscodingJob]: ...
