from typing import Protocol
from domain.entities.review import Review

class ReviewRepositoryProtocol(Protocol):
    def save(self, review: Review) -> Review: ...
    def find_all(self) -> list[Review]: ...
    def find_by_film(self, film_title: str) -> list[Review]: ...
